# netlify.toml (repo root)
[build]
  base    = "deepfake_detection_agent/frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE = "https://truthlens-ispk.onrender.com"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200