[build]
  base    = "deepfake_detection_agent/frontend"
  publish = "deepfake_detection_agent/frontend/dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200